package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgentHasAdditionalattributevalueId generated by hbm2java
 */
@Embeddable
public class AgentHasAdditionalattributevalueId implements java.io.Serializable {

	private int agentId;
	private String attributeId;

	public AgentHasAdditionalattributevalueId() {
	}

	public AgentHasAdditionalattributevalueId(int agentId, String attributeId) {
		this.agentId = agentId;
		this.attributeId = attributeId;
	}

	@Column(name = "Agent_Id", nullable = false)
	public int getAgentId() {
		return this.agentId;
	}

	public void setAgentId(int agentId) {
		this.agentId = agentId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgentHasAdditionalattributevalueId))
			return false;
		AgentHasAdditionalattributevalueId castOther = (AgentHasAdditionalattributevalueId) other;

		return (this.getAgentId() == castOther.getAgentId())
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAgentId();
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
