package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 10, 2013 2:10:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * AgentHasAdditionalattributevalueId generated by hbm2java
 */
@Embeddable
public class AgentHasAdditionalattributevalueId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8229771783359317622L;
	private Agent agent;
	private Attribute attribute;

	public AgentHasAdditionalattributevalueId() {
	}

	public AgentHasAdditionalattributevalueId(Agent agent, Attribute attribute) {
		this.agent = agent;
		this.attribute = attribute;
	}

	@ManyToOne
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
 
        AgentHasAdditionalattributevalueId that = (AgentHasAdditionalattributevalueId) o;
 
        if (agent != null ? !agent.equals(that.agent) : that.agent != null) return false;
        if (attribute != null ? !attribute.equals(that.attribute) : that.attribute != null)
            return false;
 
        return true;
    }
 
    public int hashCode() {
        int result;
        result = (agent != null ? agent.hashCode() : 0);
        result = 31 * result + (attribute != null ? attribute.hashCode() : 0);
        return result;
    }

}
