package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgentHasAdditionalattributevalue generated by hbm2java
 */
@Entity
@Table(name = "agent_has_additionalattributevalue", catalog = "rea")
public class AgentHasAdditionalattributevalue implements java.io.Serializable {

	private AgentHasAdditionalattributevalueId id;
	private Attribute attribute;
	private Agent agent;
	private Double numeric;
	private String textual;
	private Boolean boolean_;
	private Date datetime;

	public AgentHasAdditionalattributevalue() {
	}

	public AgentHasAdditionalattributevalue(
			AgentHasAdditionalattributevalueId id, Attribute attribute,
			Agent agent) {
		this.id = id;
		this.attribute = attribute;
		this.agent = agent;
	}

	public AgentHasAdditionalattributevalue(
			AgentHasAdditionalattributevalueId id, Attribute attribute,
			Agent agent, Double numeric, String textual, Boolean boolean_,
			Date datetime) {
		this.id = id;
		this.attribute = attribute;
		this.agent = agent;
		this.numeric = numeric;
		this.textual = textual;
		this.boolean_ = boolean_;
		this.datetime = datetime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "agentId", column = @Column(name = "Agent_Id", nullable = false)),
			@AttributeOverride(name = "attributeId", column = @Column(name = "Attribute_Id", nullable = false, length = 150)) })
	public AgentHasAdditionalattributevalueId getId() {
		return this.id;
	}

	public void setId(AgentHasAdditionalattributevalueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Attribute_Id", nullable = false, insertable = false, updatable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Agent_Id", nullable = false, insertable = false, updatable = false)
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@Column(name = "Numeric", precision = 22, scale = 0)
	public Double getNumeric() {
		return this.numeric;
	}

	public void setNumeric(Double numeric) {
		this.numeric = numeric;
	}

	@Column(name = "Textual", length = 45)
	public String getTextual() {
		return this.textual;
	}

	public void setTextual(String textual) {
		this.textual = textual;
	}

	@Column(name = "Boolean")
	public Boolean getBoolean_() {
		return this.boolean_;
	}

	public void setBoolean_(Boolean boolean_) {
		this.boolean_ = boolean_;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
