package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgenttypeHasAdditionalattributeId generated by hbm2java
 */
@Embeddable
public class AgenttypeHasAdditionalattributeId implements java.io.Serializable {

	private String attributeId;
	private String agentTypeId;

	public AgenttypeHasAdditionalattributeId() {
	}

	public AgenttypeHasAdditionalattributeId(String attributeId,
			String agentTypeId) {
		this.attributeId = attributeId;
		this.agentTypeId = agentTypeId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "AgentType_Id", nullable = false, length = 150)
	public String getAgentTypeId() {
		return this.agentTypeId;
	}

	public void setAgentTypeId(String agentTypeId) {
		this.agentTypeId = agentTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgenttypeHasAdditionalattributeId))
			return false;
		AgenttypeHasAdditionalattributeId castOther = (AgenttypeHasAdditionalattributeId) other;

		return ((this.getAttributeId() == castOther.getAttributeId()) || (this
				.getAttributeId() != null && castOther.getAttributeId() != null && this
				.getAttributeId().equals(castOther.getAttributeId())))
				&& ((this.getAgentTypeId() == castOther.getAgentTypeId()) || (this
						.getAgentTypeId() != null
						&& castOther.getAgentTypeId() != null && this
						.getAgentTypeId().equals(castOther.getAgentTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		result = 37
				* result
				+ (getAgentTypeId() == null ? 0 : this.getAgentTypeId()
						.hashCode());
		return result;
	}

}
