package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 12, 2013 8:47:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import master.realist.REAlistGUIGenerator.shared.dto.AttributeDTO;

/**
 * Attribute generated by hbm2java
 */
@Entity
@Table(name = "attribute", catalog = "rea")
public class Attribute implements java.io.Serializable {

	private String id;
	private String name;
	private String datatype;
	private Set<EventHasAdditionalattributevalue> eventHasAdditionalattributevalues = new HashSet<EventHasAdditionalattributevalue>(
			0);
	private Set<ResourcetypeHasAdditionalattribute> resourcetypeHasAdditionalattributes = new HashSet<ResourcetypeHasAdditionalattribute>(
			0);
	private Set<EventtypestockflowHasAdditionalattribute> eventtypestockflowHasAdditionalattributes = new HashSet<EventtypestockflowHasAdditionalattribute>(
			0);
	private Set<EventtypeparticipationHasAdditionalattributeattribute> eventtypeparticipationHasAdditionalattributeattributes = new HashSet<EventtypeparticipationHasAdditionalattributeattribute>(
			0);
	private Set<ResourceHasAdditionalattributevalue> resourceHasAdditionalattributevalues = new HashSet<ResourceHasAdditionalattributevalue>(
			0);
	private Set<Identifiablebulkresource> identifiablebulkresources = new HashSet<Identifiablebulkresource>(
			0);
	private Set<AgenttypeHasAdditionalattribute> agenttypeHasAdditionalattributes = new HashSet<AgenttypeHasAdditionalattribute>(
			0);
	private Set<EventtypeHasAdditionalattribute> eventtypeHasAdditionalattributes = new HashSet<EventtypeHasAdditionalattribute>(
			0);

	/**
	 * Added constructor to convert a attributedto object to an attribute object
	 * Needed to save in the DB
	 * @param attrdto
	 */
	public Attribute(AttributeDTO attrdto){
		this.id = attrdto.getId();
		this.name = attrdto.getName();
		this.datatype = attrdto.getDatatype();
	}
	
	public Attribute() {
	}

	public Attribute(String id) {
		this.id = id;
	}

	public Attribute(
			String id,
			String name,
			String datatype,
			Set<EventHasAdditionalattributevalue> eventHasAdditionalattributevalues,
			Set<ResourcetypeHasAdditionalattribute> resourcetypeHasAdditionalattributes,
			Set<EventtypestockflowHasAdditionalattribute> eventtypestockflowHasAdditionalattributes,
			Set<EventtypeparticipationHasAdditionalattributeattribute> eventtypeparticipationHasAdditionalattributeattributes,
			Set<ResourceHasAdditionalattributevalue> resourceHasAdditionalattributevalues,
			Set<Identifiablebulkresource> identifiablebulkresources,
			Set<AgenttypeHasAdditionalattribute> agenttypeHasAdditionalattributes,
			Set<EventtypeHasAdditionalattribute> eventtypeHasAdditionalattributes) {
		this.id = id;
		this.name = name;
		this.datatype = datatype;
		this.eventHasAdditionalattributevalues = eventHasAdditionalattributevalues;
		this.resourcetypeHasAdditionalattributes = resourcetypeHasAdditionalattributes;
		this.eventtypestockflowHasAdditionalattributes = eventtypestockflowHasAdditionalattributes;
		this.eventtypeparticipationHasAdditionalattributeattributes = eventtypeparticipationHasAdditionalattributeattributes;
		this.resourceHasAdditionalattributevalues = resourceHasAdditionalattributevalues;
		this.identifiablebulkresources = identifiablebulkresources;
		this.agenttypeHasAdditionalattributes = agenttypeHasAdditionalattributes;
		this.eventtypeHasAdditionalattributes = eventtypeHasAdditionalattributes;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false, length = 150)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Datatype", length = 45)
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<EventHasAdditionalattributevalue> getEventHasAdditionalattributevalues() {
		return this.eventHasAdditionalattributevalues;
	}

	public void setEventHasAdditionalattributevalues(
			Set<EventHasAdditionalattributevalue> eventHasAdditionalattributevalues) {
		this.eventHasAdditionalattributevalues = eventHasAdditionalattributevalues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<ResourcetypeHasAdditionalattribute> getResourcetypeHasAdditionalattributes() {
		return this.resourcetypeHasAdditionalattributes;
	}

	public void setResourcetypeHasAdditionalattributes(
			Set<ResourcetypeHasAdditionalattribute> resourcetypeHasAdditionalattributes) {
		this.resourcetypeHasAdditionalattributes = resourcetypeHasAdditionalattributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<EventtypestockflowHasAdditionalattribute> getEventtypestockflowHasAdditionalattributes() {
		return this.eventtypestockflowHasAdditionalattributes;
	}

	public void setEventtypestockflowHasAdditionalattributes(
			Set<EventtypestockflowHasAdditionalattribute> eventtypestockflowHasAdditionalattributes) {
		this.eventtypestockflowHasAdditionalattributes = eventtypestockflowHasAdditionalattributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<EventtypeparticipationHasAdditionalattributeattribute> getEventtypeparticipationHasAdditionalattributeattributes() {
		return this.eventtypeparticipationHasAdditionalattributeattributes;
	}

	public void setEventtypeparticipationHasAdditionalattributeattributes(
			Set<EventtypeparticipationHasAdditionalattributeattribute> eventtypeparticipationHasAdditionalattributeattributes) {
		this.eventtypeparticipationHasAdditionalattributeattributes = eventtypeparticipationHasAdditionalattributeattributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<ResourceHasAdditionalattributevalue> getResourceHasAdditionalattributevalues() {
		return this.resourceHasAdditionalattributevalues;
	}

	public void setResourceHasAdditionalattributevalues(
			Set<ResourceHasAdditionalattributevalue> resourceHasAdditionalattributevalues) {
		this.resourceHasAdditionalattributevalues = resourceHasAdditionalattributevalues;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "identifiablebulkresource_has_additionalattributevalue", catalog = "rea", joinColumns = { @JoinColumn(name = "Attribute_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "IdentifiableBulkResource_Id", nullable = false, updatable = false) })
	public Set<Identifiablebulkresource> getIdentifiablebulkresources() {
		return this.identifiablebulkresources;
	}

	public void setIdentifiablebulkresources(
			Set<Identifiablebulkresource> identifiablebulkresources) {
		this.identifiablebulkresources = identifiablebulkresources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<AgenttypeHasAdditionalattribute> getAgenttypeHasAdditionalattributes() {
		return this.agenttypeHasAdditionalattributes;
	}

	public void setAgenttypeHasAdditionalattributes(
			Set<AgenttypeHasAdditionalattribute> agenttypeHasAdditionalattributes) {
		this.agenttypeHasAdditionalattributes = agenttypeHasAdditionalattributes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attribute")
	public Set<EventtypeHasAdditionalattribute> getEventtypeHasAdditionalattributes() {
		return this.eventtypeHasAdditionalattributes;
	}

	public void setEventtypeHasAdditionalattributes(
			Set<EventtypeHasAdditionalattribute> eventtypeHasAdditionalattributes) {
		this.eventtypeHasAdditionalattributes = eventtypeHasAdditionalattributes;
	}

}
