package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Claimstatus generated by hbm2java
 */
@Entity
@Table(name = "claimstatus", catalog = "rea")
public class Claimstatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set<Claim> claims = new HashSet<Claim>(0);

	public Claimstatus() {
	}

	public Claimstatus(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public Claimstatus(int id, String status, Set<Claim> claims) {
		this.id = id;
		this.status = status;
		this.claims = claims;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "claimstatus")
	public Set<Claim> getClaims() {
		return this.claims;
	}

	public void setClaims(Set<Claim> claims) {
		this.claims = claims;
	}

}
