package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 12, 2013 8:47:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Claimtype generated by hbm2java
 */
@Entity
@Table(name = "claimtype", catalog = "rea")
public class Claimtype implements java.io.Serializable {

	private String id;
	private String name;
	private Set<Dualitytype> dualitytypes = new HashSet<Dualitytype>(0);
	private Set<Claim> claims = new HashSet<Claim>(0);

	public Claimtype() {
	}

	public Claimtype(String id) {
		this.id = id;
	}

	public Claimtype(String id, String name, Set<Dualitytype> dualitytypes,
			Set<Claim> claims) {
		this.id = id;
		this.name = name;
		this.dualitytypes = dualitytypes;
		this.claims = claims;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false, length = 150)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dualitytype_allows_claimtype", catalog = "rea", joinColumns = { @JoinColumn(name = "ClaimType_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "DualityType_Id", nullable = false, updatable = false) })
	public Set<Dualitytype> getDualitytypes() {
		return this.dualitytypes;
	}

	public void setDualitytypes(Set<Dualitytype> dualitytypes) {
		this.dualitytypes = dualitytypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "claimtype")
	public Set<Claim> getClaims() {
		return this.claims;
	}

	public void setClaims(Set<Claim> claims) {
		this.claims = claims;
	}

}
