package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClaimHasLocationId generated by hbm2java
 */
@Embeddable
public class ClaimHasLocationId implements java.io.Serializable {

	private int claimId;
	private int locationId;
	private int locationTypeId;

	public ClaimHasLocationId() {
	}

	public ClaimHasLocationId(int claimId, int locationId, int locationTypeId) {
		this.claimId = claimId;
		this.locationId = locationId;
		this.locationTypeId = locationTypeId;
	}

	@Column(name = "Claim_Id", nullable = false)
	public int getClaimId() {
		return this.claimId;
	}

	public void setClaimId(int claimId) {
		this.claimId = claimId;
	}

	@Column(name = "Location_Id", nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LocationType_Id", nullable = false)
	public int getLocationTypeId() {
		return this.locationTypeId;
	}

	public void setLocationTypeId(int locationTypeId) {
		this.locationTypeId = locationTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClaimHasLocationId))
			return false;
		ClaimHasLocationId castOther = (ClaimHasLocationId) other;

		return (this.getClaimId() == castOther.getClaimId())
				&& (this.getLocationId() == castOther.getLocationId())
				&& (this.getLocationTypeId() == castOther.getLocationTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaimId();
		result = 37 * result + this.getLocationId();
		result = 37 * result + this.getLocationTypeId();
		return result;
	}

}
