package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 10, 2013 2:10:07 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommitmentHasLocation generated by hbm2java
 */
@Entity
@Table(name = "commitment_has_location", catalog = "rea")
public class CommitmentHasLocation implements java.io.Serializable {

	private CommitmentHasLocationId id;
	private Location location;
	private Locationtype locationtype;
	private Commitment commitment;

	public CommitmentHasLocation() {
	}

	public CommitmentHasLocation(CommitmentHasLocationId id, Location location,
			Locationtype locationtype, Commitment commitment) {
		this.id = id;
		this.location = location;
		this.locationtype = locationtype;
		this.commitment = commitment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "commitmentId", column = @Column(name = "Commitment_Id", nullable = false)),
			@AttributeOverride(name = "locationId", column = @Column(name = "Location_Id", nullable = false)),
			@AttributeOverride(name = "locationTypeId", column = @Column(name = "LocationType_Id", nullable = false)) })
	public CommitmentHasLocationId getId() {
		return this.id;
	}

	public void setId(CommitmentHasLocationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Location_Id", nullable = false, insertable = false, updatable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LocationType_Id", nullable = false, insertable = false, updatable = false)
	public Locationtype getLocationtype() {
		return this.locationtype;
	}

	public void setLocationtype(Locationtype locationtype) {
		this.locationtype = locationtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Commitment_Id", nullable = false, insertable = false, updatable = false)
	public Commitment getCommitment() {
		return this.commitment;
	}

	public void setCommitment(Commitment commitment) {
		this.commitment = commitment;
	}

}
