package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommitmentParticipationSpecification generated by hbm2java
 */
@Entity
@Table(name = "commitment_participation_specification", catalog = "rea")
public class CommitmentParticipationSpecification implements
		java.io.Serializable {

	private CommitmentParticipationSpecificationId id;
	private Agenttype agenttype;
	private Commitment commitment;
	private Integer quantity;

	public CommitmentParticipationSpecification() {
	}

	public CommitmentParticipationSpecification(
			CommitmentParticipationSpecificationId id, Agenttype agenttype,
			Commitment commitment) {
		this.id = id;
		this.agenttype = agenttype;
		this.commitment = commitment;
	}

	public CommitmentParticipationSpecification(
			CommitmentParticipationSpecificationId id, Agenttype agenttype,
			Commitment commitment, Integer quantity) {
		this.id = id;
		this.agenttype = agenttype;
		this.commitment = commitment;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "commitmentId", column = @Column(name = "Commitment_Id", nullable = false)),
			@AttributeOverride(name = "agentTypeId", column = @Column(name = "AgentType_Id", nullable = false, length = 150)) })
	public CommitmentParticipationSpecificationId getId() {
		return this.id;
	}

	public void setId(CommitmentParticipationSpecificationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AgentType_Id", nullable = false, insertable = false, updatable = false)
	public Agenttype getAgenttype() {
		return this.agenttype;
	}

	public void setAgenttype(Agenttype agenttype) {
		this.agenttype = agenttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Commitment_Id", nullable = false, insertable = false, updatable = false)
	public Commitment getCommitment() {
		return this.commitment;
	}

	public void setCommitment(Commitment commitment) {
		this.commitment = commitment;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
