package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommitmentParticipationSpecificationId generated by hbm2java
 */
@Embeddable
public class CommitmentParticipationSpecificationId implements
		java.io.Serializable {

	private int commitmentId;
	private String agentTypeId;

	public CommitmentParticipationSpecificationId() {
	}

	public CommitmentParticipationSpecificationId(int commitmentId,
			String agentTypeId) {
		this.commitmentId = commitmentId;
		this.agentTypeId = agentTypeId;
	}

	@Column(name = "Commitment_Id", nullable = false)
	public int getCommitmentId() {
		return this.commitmentId;
	}

	public void setCommitmentId(int commitmentId) {
		this.commitmentId = commitmentId;
	}

	@Column(name = "AgentType_Id", nullable = false, length = 150)
	public String getAgentTypeId() {
		return this.agentTypeId;
	}

	public void setAgentTypeId(String agentTypeId) {
		this.agentTypeId = agentTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommitmentParticipationSpecificationId))
			return false;
		CommitmentParticipationSpecificationId castOther = (CommitmentParticipationSpecificationId) other;

		return (this.getCommitmentId() == castOther.getCommitmentId())
				&& ((this.getAgentTypeId() == castOther.getAgentTypeId()) || (this
						.getAgentTypeId() != null
						&& castOther.getAgentTypeId() != null && this
						.getAgentTypeId().equals(castOther.getAgentTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommitmentId();
		result = 37
				* result
				+ (getAgentTypeId() == null ? 0 : this.getAgentTypeId()
						.hashCode());
		return result;
	}

}
