package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 12, 2013 8:47:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contracttype generated by hbm2java
 */
@Entity
@Table(name = "contracttype", catalog = "rea")
public class Contracttype implements java.io.Serializable {

	private String id;
	private Agenttype agenttypeByDecrementAgentType;
	private Agenttype agenttypeByIncrementAgentType;
	private String name;
	private boolean isSchedule;
	private Set<Negotiation> negotiations = new HashSet<Negotiation>(0);
	private Set<Contract> contracts = new HashSet<Contract>(0);
	private Set<Dualitytype> dualitytypes = new HashSet<Dualitytype>(0);

	public Contracttype() {
	}

	public Contracttype(String id, Agenttype agenttypeByDecrementAgentType,
			Agenttype agenttypeByIncrementAgentType, boolean isSchedule) {
		this.id = id;
		this.agenttypeByDecrementAgentType = agenttypeByDecrementAgentType;
		this.agenttypeByIncrementAgentType = agenttypeByIncrementAgentType;
		this.isSchedule = isSchedule;
	}

	public Contracttype(String id, Agenttype agenttypeByDecrementAgentType,
			Agenttype agenttypeByIncrementAgentType, String name,
			boolean isSchedule, Set<Negotiation> negotiations,
			Set<Contract> contracts, Set<Dualitytype> dualitytypes) {
		this.id = id;
		this.agenttypeByDecrementAgentType = agenttypeByDecrementAgentType;
		this.agenttypeByIncrementAgentType = agenttypeByIncrementAgentType;
		this.name = name;
		this.isSchedule = isSchedule;
		this.negotiations = negotiations;
		this.contracts = contracts;
		this.dualitytypes = dualitytypes;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false, length = 150)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DecrementAgentType", nullable = false)
	public Agenttype getAgenttypeByDecrementAgentType() {
		return this.agenttypeByDecrementAgentType;
	}

	public void setAgenttypeByDecrementAgentType(
			Agenttype agenttypeByDecrementAgentType) {
		this.agenttypeByDecrementAgentType = agenttypeByDecrementAgentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IncrementAgentType", nullable = false)
	public Agenttype getAgenttypeByIncrementAgentType() {
		return this.agenttypeByIncrementAgentType;
	}

	public void setAgenttypeByIncrementAgentType(
			Agenttype agenttypeByIncrementAgentType) {
		this.agenttypeByIncrementAgentType = agenttypeByIncrementAgentType;
	}

	@Column(name = "Name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IsSchedule", nullable = false)
	public boolean isIsSchedule() {
		return this.isSchedule;
	}

	public void setIsSchedule(boolean isSchedule) {
		this.isSchedule = isSchedule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contracttype")
	public Set<Negotiation> getNegotiations() {
		return this.negotiations;
	}

	public void setNegotiations(Set<Negotiation> negotiations) {
		this.negotiations = negotiations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contracttype")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contracttype_allows_dualitytype", catalog = "rea", joinColumns = { @JoinColumn(name = "ContractType_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "DualityType_Id", nullable = false, updatable = false) })
	public Set<Dualitytype> getDualitytypes() {
		return this.dualitytypes;
	}

	public void setDualitytypes(Set<Dualitytype> dualitytypes) {
		this.dualitytypes = dualitytypes;
	}

}
