package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dualitystatus generated by hbm2java
 */
@Entity
@Table(name = "dualitystatus", catalog = "rea")
public class Dualitystatus implements java.io.Serializable {

	private int id;
	private String status;
	private Set<Duality> dualities = new HashSet<Duality>(0);

	public Dualitystatus() {
	}

	public Dualitystatus(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public Dualitystatus(int id, String status, Set<Duality> dualities) {
		this.id = id;
		this.status = status;
		this.dualities = dualities;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dualitystatus")
	public Set<Duality> getDualities() {
		return this.dualities;
	}

	public void setDualities(Set<Duality> dualities) {
		this.dualities = dualities;
	}

}
