package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 18, 2013 3:42:47 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import master.realist.REAlistGUIGenerator.shared.dto.EventHasAdditionalattributevalueDTO;

/**
 * EventHasAdditionalattributevalue generated by hbm2java
 */
@Entity
@Table(name = "event_has_additionalattributevalue", catalog = "rea")
public class EventHasAdditionalattributevalue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 538550730026629457L;
	private EventHasAdditionalattributevalueId id;
	private Event event;
	private Attribute attribute;
	private Double numericValue;
	private String textualValue;
	private Boolean booleanValue;
	private Date datetimeValue;

	/**
	 * Added constructor to convert a dualitydto object to a duality object
	 * Needed to save in the DB
	 * @param dualityDTO
	 */
	public EventHasAdditionalattributevalue(EventHasAdditionalattributevalueDTO addvaluedto){
		this.id = new EventHasAdditionalattributevalueId(addvaluedto.getId());
		this.event = new Event(addvaluedto.getEvent());
		this.attribute = new Attribute(addvaluedto.getAttribute());
		this.numericValue = addvaluedto.getNumeric();
		this.textualValue = addvaluedto.getTextual();
		this.booleanValue = addvaluedto.getBoolean_();
		this.datetimeValue = addvaluedto.getDatetime();
	}
	
	
	public EventHasAdditionalattributevalue() {
	}

	public EventHasAdditionalattributevalue(
			EventHasAdditionalattributevalueId id, Event event,
			Attribute attribute) {
		this.id = id;
		this.event = event;
		this.attribute = attribute;
	}

	public EventHasAdditionalattributevalue(
			EventHasAdditionalattributevalueId id, Event event,
			Attribute attribute, Double numericValue, String textualValue,
			Boolean booleanValue, Date datetimeValue) {
		this.id = id;
		this.event = event;
		this.attribute = attribute;
		this.numericValue = numericValue;
		this.textualValue = textualValue;
		this.booleanValue = booleanValue;
		this.datetimeValue = datetimeValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "eventId", column = @Column(name = "Event_Id", nullable = false)),
			@AttributeOverride(name = "attributeId", column = @Column(name = "Attribute_Id", nullable = false, length = 150)) })
	public EventHasAdditionalattributevalueId getId() {
		return this.id;
	}

	public void setId(EventHasAdditionalattributevalueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Event_Id", nullable = false, insertable = false, updatable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Attribute_Id", nullable = false, insertable = false, updatable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@Column(name = "Numeric_Value", precision = 22, scale = 0)
	public Double getNumericValue() {
		return this.numericValue;
	}

	public void setNumericValue(Double numericValue) {
		this.numericValue = numericValue;
	}

	@Column(name = "Textual_Value", length = 45)
	public String getTextualValue() {
		return this.textualValue;
	}

	public void setTextualValue(String textualValue) {
		this.textualValue = textualValue;
	}

	@Column(name = "Boolean_Value")
	public Boolean getBooleanValue() {
		return this.booleanValue;
	}

	public void setBooleanValue(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datetime_Value", length = 19)
	public Date getDatetimeValue() {
		return this.datetimeValue;
	}

	public void setDatetimeValue(Date datetimeValue) {
		this.datetimeValue = datetimeValue;
	}

}
