package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventtypestockflowId generated by hbm2java
 */
@Embeddable
public class EventtypestockflowId implements java.io.Serializable {

	private String eventTypeId;
	private String resourceTypeId;

	public EventtypestockflowId() {
	}

	public EventtypestockflowId(String eventTypeId, String resourceTypeId) {
		this.eventTypeId = eventTypeId;
		this.resourceTypeId = resourceTypeId;
	}

	@Column(name = "EventType_Id", nullable = false, length = 150)
	public String getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(String eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	@Column(name = "ResourceType_Id", nullable = false, length = 150)
	public String getResourceTypeId() {
		return this.resourceTypeId;
	}

	public void setResourceTypeId(String resourceTypeId) {
		this.resourceTypeId = resourceTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtypestockflowId))
			return false;
		EventtypestockflowId castOther = (EventtypestockflowId) other;

		return ((this.getEventTypeId() == castOther.getEventTypeId()) || (this
				.getEventTypeId() != null && castOther.getEventTypeId() != null && this
				.getEventTypeId().equals(castOther.getEventTypeId())))
				&& ((this.getResourceTypeId() == castOther.getResourceTypeId()) || (this
						.getResourceTypeId() != null
						&& castOther.getResourceTypeId() != null && this
						.getResourceTypeId().equals(
								castOther.getResourceTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEventTypeId() == null ? 0 : this.getEventTypeId()
						.hashCode());
		result = 37
				* result
				+ (getResourceTypeId() == null ? 0 : this.getResourceTypeId()
						.hashCode());
		return result;
	}

}
