package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 10, 2013 2:10:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventHasLocationId generated by hbm2java
 */
@Embeddable
public class EventHasLocationId implements java.io.Serializable {

	private int eventId;
	private int locationId;
	private int locationTypeId;

	public EventHasLocationId() {
	}

	public EventHasLocationId(int eventId, int locationId, int locationTypeId) {
		this.eventId = eventId;
		this.locationId = locationId;
		this.locationTypeId = locationTypeId;
	}

	@Column(name = "Event_Id", nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "Location_Id", nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LocationType_Id", nullable = false)
	public int getLocationTypeId() {
		return this.locationTypeId;
	}

	public void setLocationTypeId(int locationTypeId) {
		this.locationTypeId = locationTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventHasLocationId))
			return false;
		EventHasLocationId castOther = (EventHasLocationId) other;

		return (this.getEventId() == castOther.getEventId())
				&& (this.getLocationId() == castOther.getLocationId())
				&& (this.getLocationTypeId() == castOther.getLocationTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEventId();
		result = 37 * result + this.getLocationId();
		result = 37 * result + this.getLocationTypeId();
		return result;
	}

}
