package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventtypeparticipationHasAdditionalattributeId generated by hbm2java
 */
@Embeddable
public class EventtypeparticipationHasAdditionalattributeId implements
		java.io.Serializable {

	private String eventTypeParticipationEventTypeId;
	private String eventTypeParticipationAgentTypeId;
	private String attributeId;

	public EventtypeparticipationHasAdditionalattributeId() {
	}

	public EventtypeparticipationHasAdditionalattributeId(
			String eventTypeParticipationEventTypeId,
			String eventTypeParticipationAgentTypeId, String attributeId) {
		this.eventTypeParticipationEventTypeId = eventTypeParticipationEventTypeId;
		this.eventTypeParticipationAgentTypeId = eventTypeParticipationAgentTypeId;
		this.attributeId = attributeId;
	}

	@Column(name = "EventTypeParticipation_EventType_Id", nullable = false, length = 150)
	public String getEventTypeParticipationEventTypeId() {
		return this.eventTypeParticipationEventTypeId;
	}

	public void setEventTypeParticipationEventTypeId(
			String eventTypeParticipationEventTypeId) {
		this.eventTypeParticipationEventTypeId = eventTypeParticipationEventTypeId;
	}

	@Column(name = "EventTypeParticipation_AgentType_Id", nullable = false, length = 150)
	public String getEventTypeParticipationAgentTypeId() {
		return this.eventTypeParticipationAgentTypeId;
	}

	public void setEventTypeParticipationAgentTypeId(
			String eventTypeParticipationAgentTypeId) {
		this.eventTypeParticipationAgentTypeId = eventTypeParticipationAgentTypeId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtypeparticipationHasAdditionalattributeId))
			return false;
		EventtypeparticipationHasAdditionalattributeId castOther = (EventtypeparticipationHasAdditionalattributeId) other;

		return ((this.getEventTypeParticipationEventTypeId() == castOther
				.getEventTypeParticipationEventTypeId()) || (this
				.getEventTypeParticipationEventTypeId() != null
				&& castOther.getEventTypeParticipationEventTypeId() != null && this
				.getEventTypeParticipationEventTypeId().equals(
						castOther.getEventTypeParticipationEventTypeId())))
				&& ((this.getEventTypeParticipationAgentTypeId() == castOther
						.getEventTypeParticipationAgentTypeId()) || (this
						.getEventTypeParticipationAgentTypeId() != null
						&& castOther.getEventTypeParticipationAgentTypeId() != null && this
						.getEventTypeParticipationAgentTypeId()
						.equals(castOther
								.getEventTypeParticipationAgentTypeId())))
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEventTypeParticipationEventTypeId() == null ? 0 : this
						.getEventTypeParticipationEventTypeId().hashCode());
		result = 37
				* result
				+ (getEventTypeParticipationAgentTypeId() == null ? 0 : this
						.getEventTypeParticipationAgentTypeId().hashCode());
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
