package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventtypestockflowHasAdditionalattributeId generated by hbm2java
 */
@Embeddable
public class EventtypestockflowHasAdditionalattributeId implements
		java.io.Serializable {

	private String eventTypeStockflowEventTypeId;
	private String eventTypeStockflowResourceTypeId;
	private String attributeId;

	public EventtypestockflowHasAdditionalattributeId() {
	}

	public EventtypestockflowHasAdditionalattributeId(
			String eventTypeStockflowEventTypeId,
			String eventTypeStockflowResourceTypeId, String attributeId) {
		this.eventTypeStockflowEventTypeId = eventTypeStockflowEventTypeId;
		this.eventTypeStockflowResourceTypeId = eventTypeStockflowResourceTypeId;
		this.attributeId = attributeId;
	}

	@Column(name = "EventTypeStockflow_EventType_Id", nullable = false, length = 150)
	public String getEventTypeStockflowEventTypeId() {
		return this.eventTypeStockflowEventTypeId;
	}

	public void setEventTypeStockflowEventTypeId(
			String eventTypeStockflowEventTypeId) {
		this.eventTypeStockflowEventTypeId = eventTypeStockflowEventTypeId;
	}

	@Column(name = "EventTypeStockflow_ResourceType_Id", nullable = false, length = 150)
	public String getEventTypeStockflowResourceTypeId() {
		return this.eventTypeStockflowResourceTypeId;
	}

	public void setEventTypeStockflowResourceTypeId(
			String eventTypeStockflowResourceTypeId) {
		this.eventTypeStockflowResourceTypeId = eventTypeStockflowResourceTypeId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtypestockflowHasAdditionalattributeId))
			return false;
		EventtypestockflowHasAdditionalattributeId castOther = (EventtypestockflowHasAdditionalattributeId) other;

		return ((this.getEventTypeStockflowEventTypeId() == castOther
				.getEventTypeStockflowEventTypeId()) || (this
				.getEventTypeStockflowEventTypeId() != null
				&& castOther.getEventTypeStockflowEventTypeId() != null && this
				.getEventTypeStockflowEventTypeId().equals(
						castOther.getEventTypeStockflowEventTypeId())))
				&& ((this.getEventTypeStockflowResourceTypeId() == castOther
						.getEventTypeStockflowResourceTypeId()) || (this
						.getEventTypeStockflowResourceTypeId() != null
						&& castOther.getEventTypeStockflowResourceTypeId() != null && this
						.getEventTypeStockflowResourceTypeId()
						.equals(castOther.getEventTypeStockflowResourceTypeId())))
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEventTypeStockflowEventTypeId() == null ? 0 : this
						.getEventTypeStockflowEventTypeId().hashCode());
		result = 37
				* result
				+ (getEventTypeStockflowResourceTypeId() == null ? 0 : this
						.getEventTypeStockflowResourceTypeId().hashCode());
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
