package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventtypeparticipationHasAdditionalattributeattributeId generated by hbm2java
 */
@Embeddable
public class EventtypeparticipationHasAdditionalattributeattributeId implements
		java.io.Serializable {

	private String attributeId;
	private String eventTypeParticipationAgentTypeId;
	private String eventTypeParticipationEventTypeId;

	public EventtypeparticipationHasAdditionalattributeattributeId() {
	}

	public EventtypeparticipationHasAdditionalattributeattributeId(
			String attributeId, String eventTypeParticipationAgentTypeId,
			String eventTypeParticipationEventTypeId) {
		this.attributeId = attributeId;
		this.eventTypeParticipationAgentTypeId = eventTypeParticipationAgentTypeId;
		this.eventTypeParticipationEventTypeId = eventTypeParticipationEventTypeId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	@Column(name = "EventTypeParticipation_AgentType_Id", nullable = false, length = 150)
	public String getEventTypeParticipationAgentTypeId() {
		return this.eventTypeParticipationAgentTypeId;
	}

	public void setEventTypeParticipationAgentTypeId(
			String eventTypeParticipationAgentTypeId) {
		this.eventTypeParticipationAgentTypeId = eventTypeParticipationAgentTypeId;
	}

	@Column(name = "EventTypeParticipation_EventType_Id", nullable = false, length = 150)
	public String getEventTypeParticipationEventTypeId() {
		return this.eventTypeParticipationEventTypeId;
	}

	public void setEventTypeParticipationEventTypeId(
			String eventTypeParticipationEventTypeId) {
		this.eventTypeParticipationEventTypeId = eventTypeParticipationEventTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventtypeparticipationHasAdditionalattributeattributeId))
			return false;
		EventtypeparticipationHasAdditionalattributeattributeId castOther = (EventtypeparticipationHasAdditionalattributeattributeId) other;

		return ((this.getAttributeId() == castOther.getAttributeId()) || (this
				.getAttributeId() != null && castOther.getAttributeId() != null && this
				.getAttributeId().equals(castOther.getAttributeId())))
				&& ((this.getEventTypeParticipationAgentTypeId() == castOther
						.getEventTypeParticipationAgentTypeId()) || (this
						.getEventTypeParticipationAgentTypeId() != null
						&& castOther.getEventTypeParticipationAgentTypeId() != null && this
						.getEventTypeParticipationAgentTypeId()
						.equals(castOther
								.getEventTypeParticipationAgentTypeId())))
				&& ((this.getEventTypeParticipationEventTypeId() == castOther
						.getEventTypeParticipationEventTypeId()) || (this
						.getEventTypeParticipationEventTypeId() != null
						&& castOther.getEventTypeParticipationEventTypeId() != null && this
						.getEventTypeParticipationEventTypeId()
						.equals(castOther
								.getEventTypeParticipationEventTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		result = 37
				* result
				+ (getEventTypeParticipationAgentTypeId() == null ? 0 : this
						.getEventTypeParticipationAgentTypeId().hashCode());
		result = 37
				* result
				+ (getEventTypeParticipationEventTypeId() == null ? 0 : this
						.getEventTypeParticipationEventTypeId().hashCode());
		return result;
	}

}
