package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FactorPropertyconstraint generated by hbm2java
 */
@Entity
@Table(name = "factor_propertyconstraint", catalog = "rea")
public class FactorPropertyconstraint implements java.io.Serializable {

	private int id;
	private FactorAgenttype factorAgenttype;
	private String column;
	private String value;
	private String comparator;

	public FactorPropertyconstraint() {
	}

	public FactorPropertyconstraint(int id, FactorAgenttype factorAgenttype) {
		this.id = id;
		this.factorAgenttype = factorAgenttype;
	}

	public FactorPropertyconstraint(int id, FactorAgenttype factorAgenttype,
			String column, String value, String comparator) {
		this.id = id;
		this.factorAgenttype = factorAgenttype;
		this.column = column;
		this.value = value;
		this.comparator = comparator;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Factor_AgentType_Id", nullable = false)
	public FactorAgenttype getFactorAgenttype() {
		return this.factorAgenttype;
	}

	public void setFactorAgenttype(FactorAgenttype factorAgenttype) {
		this.factorAgenttype = factorAgenttype;
	}

	@Column(name = "Column", length = 45)
	public String getColumn() {
		return this.column;
	}

	public void setColumn(String column) {
		this.column = column;
	}

	@Column(name = "Value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "Comparator", length = 45)
	public String getComparator() {
		return this.comparator;
	}

	public void setComparator(String comparator) {
		this.comparator = comparator;
	}

}
