package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocationofresourceId generated by hbm2java
 */
@Embeddable
public class LocationofresourceId implements java.io.Serializable {

	private int resourceTypeId;
	private int locationId;

	public LocationofresourceId() {
	}

	public LocationofresourceId(int resourceTypeId, int locationId) {
		this.resourceTypeId = resourceTypeId;
		this.locationId = locationId;
	}

	@Column(name = "ResourceType_Id", nullable = false)
	public int getResourceTypeId() {
		return this.resourceTypeId;
	}

	public void setResourceTypeId(int resourceTypeId) {
		this.resourceTypeId = resourceTypeId;
	}

	@Column(name = "Location_Id", nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocationofresourceId))
			return false;
		LocationofresourceId castOther = (LocationofresourceId) other;

		return (this.getResourceTypeId() == castOther.getResourceTypeId())
				&& (this.getLocationId() == castOther.getLocationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getResourceTypeId();
		result = 37 * result + this.getLocationId();
		return result;
	}

}
