package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Negotiation generated by hbm2java
 */
@Entity
@Table(name = "negotiation", catalog = "rea")
public class Negotiation implements java.io.Serializable {

	private int id;
	private Negotiationstatus negotiationstatus;
	private Contracttype contracttype;
	private Set<Agent> agents = new HashSet<Agent>(0);
	private Set<Proposal> proposals = new HashSet<Proposal>(0);
	private Set<Contract> contracts = new HashSet<Contract>(0);

	public Negotiation() {
	}

	public Negotiation(int id, Negotiationstatus negotiationstatus,
			Contracttype contracttype) {
		this.id = id;
		this.negotiationstatus = negotiationstatus;
		this.contracttype = contracttype;
	}

	public Negotiation(int id, Negotiationstatus negotiationstatus,
			Contracttype contracttype, Set<Agent> agents,
			Set<Proposal> proposals, Set<Contract> contracts) {
		this.id = id;
		this.negotiationstatus = negotiationstatus;
		this.contracttype = contracttype;
		this.agents = agents;
		this.proposals = proposals;
		this.contracts = contracts;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status_Id", nullable = false)
	public Negotiationstatus getNegotiationstatus() {
		return this.negotiationstatus;
	}

	public void setNegotiationstatus(Negotiationstatus negotiationstatus) {
		this.negotiationstatus = negotiationstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ContractType_Id", nullable = false)
	public Contracttype getContracttype() {
		return this.contracttype;
	}

	public void setContracttype(Contracttype contracttype) {
		this.contracttype = contracttype;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "negotiation_has_agents", catalog = "rea", joinColumns = { @JoinColumn(name = "Negotiation_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Agent_Id", nullable = false, updatable = false) })
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "negotiation")
	public Set<Proposal> getProposals() {
		return this.proposals;
	}

	public void setProposals(Set<Proposal> proposals) {
		this.proposals = proposals;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contract_has_negotiation", catalog = "rea", joinColumns = { @JoinColumn(name = "Negotiation_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Contract_Id", nullable = false, updatable = false) })
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

}
