package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 18, 2013 3:42:47 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;

import javax.persistence.JoinColumn;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ParticipationHasAdditionalattributevalue generated by hbm2java
 */
@Entity
@Table(name = "participation_has_additionalattributevalue", catalog = "rea")
@AssociationOverrides({
	@AssociationOverride(name = "id.participation", 
		joinColumns = @JoinColumn(name = "Participation_Participation_Id")),
	@AssociationOverride(name = "id.attribute", 
		joinColumns = @JoinColumn(name = "Attribute_Id")) })
public class ParticipationHasAdditionalattributevalue implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2390170267636965320L;
	private ParticipationHasAdditionalattributevalueId id = new ParticipationHasAdditionalattributevalueId();
	private Double numericValue;
	private String textualValue;
	private Boolean booleanValue;
	private Date datetimeValue;

	public ParticipationHasAdditionalattributevalue() {
	}

	public ParticipationHasAdditionalattributevalue(
			ParticipationHasAdditionalattributevalueId id,
			Participation participation, Attribute attribute) {
		this.id = id;
		this.getId().setParticipation(participation);
		this.getId().setAttribute(attribute);
	}

	public ParticipationHasAdditionalattributevalue(
			ParticipationHasAdditionalattributevalueId id,
			Participation participation, Attribute attribute,
			Double numericValue, String textualValue, Boolean booleanValue,
			Date datetimeValue) {
		this.id = id;
		this.getId().setParticipation(participation);
		this.getId().setAttribute(attribute);
		this.numericValue = numericValue;
		this.textualValue = textualValue;
		this.booleanValue = booleanValue;
		this.datetimeValue = datetimeValue;
	}

	@EmbeddedId
	public ParticipationHasAdditionalattributevalueId getId() {
		return this.id;
	}

	public void setId(ParticipationHasAdditionalattributevalueId id) {
		this.id = id;
	}

	@Transient
	public Participation getParticipation() {
		return this.getId().getParticipation();
	}

	public void setParticipation(Participation participation) {
		this.getId().setParticipation(participation);
	}

	@Transient
	public Attribute getAttribute() {
		return this.getId().getAttribute();
	}

	public void setAttribute(Attribute attribute) {
		this.getId().setAttribute(attribute);
	}

	@Column(name = "Numeric_Value", precision = 22, scale = 0)
	public Double getNumericValue() {
		return this.numericValue;
	}

	public void setNumericValue(Double numericValue) {
		this.numericValue = numericValue;
	}

	@Column(name = "Textual_Value", length = 45)
	public String getTextualValue() {
		return this.textualValue;
	}

	public void setTextualValue(String textualValue) {
		this.textualValue = textualValue;
	}

	@Column(name = "Boolean_Value")
	public Boolean getBooleanValue() {
		return this.booleanValue;
	}

	public void setBooleanValue(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datetime_Value", length = 19)
	public Date getDatetimeValue() {
		return this.datetimeValue;
	}

	public void setDatetimeValue(Date datetimeValue) {
		this.datetimeValue = datetimeValue;
	}
	
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
 
		ParticipationHasAdditionalattributevalue that = (ParticipationHasAdditionalattributevalue) o;
 
		if (getId() != null ? !getId().equals(that.getId())
				: that.getId() != null)
			return false;
 
		return true;
	}
 
	public int hashCode() {
		return (getId() != null ? getId().hashCode() : 0);
	}

}
