package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 10, 2013 2:10:07 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParticipationHasAdditionalattributevalue generated by hbm2java
 */
@Entity
@Table(name = "participation_has_additionalattributevalue", catalog = "rea")
public class ParticipationHasAdditionalattributevalue implements
		java.io.Serializable {

	private ParticipationHasAdditionalattributevalueId id;
	private Participation participation;
	private Attribute attribute;
	private Double numeric;
	private String textual;
	private Boolean boolean_;
	private Date datetime;

	public ParticipationHasAdditionalattributevalue() {
	}

	public ParticipationHasAdditionalattributevalue(
			ParticipationHasAdditionalattributevalueId id,
			Participation participation, Attribute attribute) {
		this.id = id;
		this.participation = participation;
		this.attribute = attribute;
	}

	public ParticipationHasAdditionalattributevalue(
			ParticipationHasAdditionalattributevalueId id,
			Participation participation, Attribute attribute, Double numeric,
			String textual, Boolean boolean_, Date datetime) {
		this.id = id;
		this.participation = participation;
		this.attribute = attribute;
		this.numeric = numeric;
		this.textual = textual;
		this.boolean_ = boolean_;
		this.datetime = datetime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "participationParticipationId", column = @Column(name = "Participation_Participation_id", nullable = false)),
			@AttributeOverride(name = "attributeId", column = @Column(name = "Attribute_Id", nullable = false, length = 150)) })
	public ParticipationHasAdditionalattributevalueId getId() {
		return this.id;
	}

	public void setId(ParticipationHasAdditionalattributevalueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Participation_Participation_id", nullable = false, insertable = false, updatable = false)
	public Participation getParticipation() {
		return this.participation;
	}

	public void setParticipation(Participation participation) {
		this.participation = participation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Attribute_Id", nullable = false, insertable = false, updatable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@Column(name = "Numeric", precision = 22, scale = 0)
	public Double getNumeric() {
		return this.numeric;
	}

	public void setNumeric(Double numeric) {
		this.numeric = numeric;
	}

	@Column(name = "Textual", length = 45)
	public String getTextual() {
		return this.textual;
	}

	public void setTextual(String textual) {
		this.textual = textual;
	}

	@Column(name = "Boolean")
	public Boolean getBoolean_() {
		return this.boolean_;
	}

	public void setBoolean_(Boolean boolean_) {
		this.boolean_ = boolean_;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
