package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PolicyOutcome generated by hbm2java
 */
@Entity
@Table(name = "policy_outcome", catalog = "rea")
public class PolicyOutcome implements java.io.Serializable {

	private int id;
	private String value;
	private Set<Policy> policies = new HashSet<Policy>(0);

	public PolicyOutcome() {
	}

	public PolicyOutcome(int id) {
		this.id = id;
	}

	public PolicyOutcome(int id, String value, Set<Policy> policies) {
		this.id = id;
		this.value = value;
		this.policies = policies;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyOutcome")
	public Set<Policy> getPolicies() {
		return this.policies;
	}

	public void setPolicies(Set<Policy> policies) {
		this.policies = policies;
	}

}
