package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Policytype generated by hbm2java
 */
@Entity
@Table(name = "policytype", catalog = "rea")
public class Policytype implements java.io.Serializable {

	private int id;
	private String name;
	private String statement;
	private Set<Policy> policies = new HashSet<Policy>(0);

	public Policytype() {
	}

	public Policytype(int id) {
		this.id = id;
	}

	public Policytype(int id, String name, String statement,
			Set<Policy> policies) {
		this.id = id;
		this.name = name;
		this.statement = statement;
		this.policies = policies;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Statement", length = 200)
	public String getStatement() {
		return this.statement;
	}

	public void setStatement(String statement) {
		this.statement = statement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policytype")
	public Set<Policy> getPolicies() {
		return this.policies;
	}

	public void setPolicies(Set<Policy> policies) {
		this.policies = policies;
	}

}
