package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 12, 2013 8:47:49 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pricelist generated by hbm2java
 */
@Entity
@Table(name = "pricelist", catalog = "rea")
public class Pricelist implements java.io.Serializable {

	private int id;
	private Location location;
	private Agenttype agenttype;
	private Date from;
	private Date to;
	private Set<Pricepolicy> pricepolicies = new HashSet<Pricepolicy>(0);

	public Pricelist() {
	}

	public Pricelist(int id) {
		this.id = id;
	}

	public Pricelist(int id, Location location, Agenttype agenttype, Date from,
			Date to, Set<Pricepolicy> pricepolicies) {
		this.id = id;
		this.location = location;
		this.agenttype = agenttype;
		this.from = from;
		this.to = to;
		this.pricepolicies = pricepolicies;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Location_Id")
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AgentType_Id")
	public Agenttype getAgenttype() {
		return this.agenttype;
	}

	public void setAgenttype(Agenttype agenttype) {
		this.agenttype = agenttype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "From", length = 19)
	public Date getFrom() {
		return this.from;
	}

	public void setFrom(Date from) {
		this.from = from;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "To", length = 19)
	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricelist")
	public Set<Pricepolicy> getPricepolicies() {
		return this.pricepolicies;
	}

	public void setPricepolicies(Set<Pricepolicy> pricepolicies) {
		this.pricepolicies = pricepolicies;
	}

}
