package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reconciliation generated by hbm2java
 */
@Entity
@Table(name = "reconciliation", catalog = "rea")
public class Reconciliation implements java.io.Serializable {

	private ReconciliationId id;
	private Event eventByDecEventId;
	private Currency currency;
	private Event eventByIncEventId;
	private Double value;

	public Reconciliation() {
	}

	public Reconciliation(ReconciliationId id, Event eventByDecEventId,
			Event eventByIncEventId) {
		this.id = id;
		this.eventByDecEventId = eventByDecEventId;
		this.eventByIncEventId = eventByIncEventId;
	}

	public Reconciliation(ReconciliationId id, Event eventByDecEventId,
			Currency currency, Event eventByIncEventId, Double value) {
		this.id = id;
		this.eventByDecEventId = eventByDecEventId;
		this.currency = currency;
		this.eventByIncEventId = eventByIncEventId;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "incEventId", column = @Column(name = "IncEvent_Id", nullable = false)),
			@AttributeOverride(name = "decEventId", column = @Column(name = "DecEvent_Id", nullable = false)) })
	public ReconciliationId getId() {
		return this.id;
	}

	public void setId(ReconciliationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DecEvent_Id", nullable = false, insertable = false, updatable = false)
	public Event getEventByDecEventId() {
		return this.eventByDecEventId;
	}

	public void setEventByDecEventId(Event eventByDecEventId) {
		this.eventByDecEventId = eventByDecEventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Currency_Id")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IncEvent_Id", nullable = false, insertable = false, updatable = false)
	public Event getEventByIncEventId() {
		return this.eventByIncEventId;
	}

	public void setEventByIncEventId(Event eventByIncEventId) {
		this.eventByIncEventId = eventByIncEventId;
	}

	@Column(name = "Value", precision = 22, scale = 0)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
