package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 19, 2013 8:35:27 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceComposedOf generated by hbm2java
 */
@Entity
@Table(name = "resource_composed_of", catalog = "rea")
public class ResourceComposedOf implements java.io.Serializable {

	private ResourceComposedOfId id;
	private Resource resourceByResourceId;
	private Resource resourceByResourcePartId;
	private Double quantity;

	public ResourceComposedOf() {
	}

	public ResourceComposedOf(ResourceComposedOfId id,
			Resource resourceByResourceId, Resource resourceByResourcePartId) {
		this.id = id;
		this.resourceByResourceId = resourceByResourceId;
		this.resourceByResourcePartId = resourceByResourcePartId;
	}

	public ResourceComposedOf(ResourceComposedOfId id,
			Resource resourceByResourceId, Resource resourceByResourcePartId,
			Double quantity) {
		this.id = id;
		this.resourceByResourceId = resourceByResourceId;
		this.resourceByResourcePartId = resourceByResourcePartId;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "resourceId", column = @Column(name = "Resource_Id", nullable = false)),
			@AttributeOverride(name = "resourcePartId", column = @Column(name = "ResourcePart_Id", nullable = false)) })
	public ResourceComposedOfId getId() {
		return this.id;
	}

	public void setId(ResourceComposedOfId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Resource_Id", nullable = false, insertable = false, updatable = false)
	public Resource getResourceByResourceId() {
		return this.resourceByResourceId;
	}

	public void setResourceByResourceId(Resource resourceByResourceId) {
		this.resourceByResourceId = resourceByResourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ResourcePart_Id", nullable = false, insertable = false, updatable = false)
	public Resource getResourceByResourcePartId() {
		return this.resourceByResourcePartId;
	}

	public void setResourceByResourcePartId(Resource resourceByResourcePartId) {
		this.resourceByResourcePartId = resourceByResourcePartId;
	}

	@Column(name = "Quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

}
