package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 12, 2013 8:47:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourcetypeHasAdditionalattributeId generated by hbm2java
 */
@Embeddable
public class ResourcetypeHasAdditionalattributeId implements
		java.io.Serializable {

	private String resourceTypeId;
	private String attributeId;

	public ResourcetypeHasAdditionalattributeId() {
	}

	public ResourcetypeHasAdditionalattributeId(String resourceTypeId,
			String attributeId) {
		this.resourceTypeId = resourceTypeId;
		this.attributeId = attributeId;
	}

	@Column(name = "ResourceType_Id", nullable = false, length = 150)
	public String getResourceTypeId() {
		return this.resourceTypeId;
	}

	public void setResourceTypeId(String resourceTypeId) {
		this.resourceTypeId = resourceTypeId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourcetypeHasAdditionalattributeId))
			return false;
		ResourcetypeHasAdditionalattributeId castOther = (ResourcetypeHasAdditionalattributeId) other;

		return ((this.getResourceTypeId() == castOther.getResourceTypeId()) || (this
				.getResourceTypeId() != null
				&& castOther.getResourceTypeId() != null && this
				.getResourceTypeId().equals(castOther.getResourceTypeId())))
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getResourceTypeId() == null ? 0 : this.getResourceTypeId()
						.hashCode());
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
