package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 18, 2013 3:42:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * StockflowHasAdditionalattributevalueId generated by hbm2java
 */
@Embeddable
public class StockflowHasAdditionalattributevalueId implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3475082562364835048L;
	private Stockflow stockflow;
	private Attribute attribute;

	/**
	 * Default Constructor
	 */
	public StockflowHasAdditionalattributevalueId() {
	}

	public StockflowHasAdditionalattributevalueId(Stockflow stockflow,
			Attribute attribute) {
		this.stockflow = stockflow;
		this.attribute = attribute;
	}

	@ManyToOne
	public Stockflow getStockflow() {
		return this.stockflow;
	}

	public void setStockflow(Stockflow stockflow) {
		this.stockflow = stockflow;
	}

	@ManyToOne
	public Attribute getAttribute() {
		return attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
 
        StockflowHasAdditionalattributevalueId that = (StockflowHasAdditionalattributevalueId) o;
 
        if (stockflow != null ? !stockflow.equals(that.stockflow) : that.stockflow != null) return false;
        if (attribute != null ? !attribute.equals(that.attribute) : that.attribute != null)
            return false;
 
        return true;
    }
 
    public int hashCode() {
        int result;
        result = (stockflow != null ? stockflow.hashCode() : 0);
        result = 31 * result + (attribute != null ? attribute.hashCode() : 0);
        return result;
    }

}
