package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 18, 2013 3:42:47 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockflowHasAdditionalattributevalue generated by hbm2java
 */
@Entity
@Table(name = "stockflow_has_additionalattributevalue", catalog = "rea")
public class StockflowHasAdditionalattributevalue implements
		java.io.Serializable {

	private StockflowHasAdditionalattributevalueId id;
	private Stockflow stockflow;
	private Attribute attribute;
	private Double numericValue;
	private String textualValue;
	private Boolean booleanValue;
	private Date datetimeValue;

	public StockflowHasAdditionalattributevalue() {
	}

	public StockflowHasAdditionalattributevalue(
			StockflowHasAdditionalattributevalueId id, Stockflow stockflow,
			Attribute attribute) {
		this.id = id;
		this.stockflow = stockflow;
		this.attribute = attribute;
	}

	public StockflowHasAdditionalattributevalue(
			StockflowHasAdditionalattributevalueId id, Stockflow stockflow,
			Attribute attribute, Double numericValue, String textualValue,
			Boolean booleanValue, Date datetimeValue) {
		this.id = id;
		this.stockflow = stockflow;
		this.attribute = attribute;
		this.numericValue = numericValue;
		this.textualValue = textualValue;
		this.booleanValue = booleanValue;
		this.datetimeValue = datetimeValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stockflowId", column = @Column(name = "Stockflow_Id", nullable = false)),
			@AttributeOverride(name = "attributeId", column = @Column(name = "Attribute_Id", nullable = false, length = 150)) })
	public StockflowHasAdditionalattributevalueId getId() {
		return this.id;
	}

	public void setId(StockflowHasAdditionalattributevalueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Stockflow_Id", nullable = false, insertable = false, updatable = false)
	public Stockflow getStockflow() {
		return this.stockflow;
	}

	public void setStockflow(Stockflow stockflow) {
		this.stockflow = stockflow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Attribute_Id", nullable = false, insertable = false, updatable = false)
	public Attribute getAttribute() {
		return this.attribute;
	}

	public void setAttribute(Attribute attribute) {
		this.attribute = attribute;
	}

	@Column(name = "Numeric_Value", precision = 22, scale = 0)
	public Double getNumericValue() {
		return this.numericValue;
	}

	public void setNumericValue(Double numericValue) {
		this.numericValue = numericValue;
	}

	@Column(name = "Textual_Value", length = 45)
	public String getTextualValue() {
		return this.textualValue;
	}

	public void setTextualValue(String textualValue) {
		this.textualValue = textualValue;
	}

	@Column(name = "Boolean_Value")
	public Boolean getBooleanValue() {
		return this.booleanValue;
	}

	public void setBooleanValue(Boolean booleanValue) {
		this.booleanValue = booleanValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Datetime_Value", length = 19)
	public Date getDatetimeValue() {
		return this.datetimeValue;
	}

	public void setDatetimeValue(Date datetimeValue) {
		this.datetimeValue = datetimeValue;
	}

}
