package master.realist.REAlistGUIGenerator.shared.model;

// Generated Dec 10, 2013 2:10:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockflowHasAdditionalattributevalueId generated by hbm2java
 */
@Embeddable
public class StockflowHasAdditionalattributevalueId implements
		java.io.Serializable {

	private int stockflowId;
	private String attributeId;

	public StockflowHasAdditionalattributevalueId() {
	}

	public StockflowHasAdditionalattributevalueId(int stockflowId,
			String attributeId) {
		this.stockflowId = stockflowId;
		this.attributeId = attributeId;
	}

	@Column(name = "Stockflow_Id", nullable = false)
	public int getStockflowId() {
		return this.stockflowId;
	}

	public void setStockflowId(int stockflowId) {
		this.stockflowId = stockflowId;
	}

	@Column(name = "Attribute_Id", nullable = false, length = 150)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockflowHasAdditionalattributevalueId))
			return false;
		StockflowHasAdditionalattributevalueId castOther = (StockflowHasAdditionalattributevalueId) other;

		return (this.getStockflowId() == castOther.getStockflowId())
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStockflowId();
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
