package master.realist.REAlistGUIGenerator.shared.model;

// Generated Nov 5, 2013 2:01:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax", catalog = "rea")
public class Tax implements java.io.Serializable {

	private int id;
	private Resource resource;
	private double percentage;
	private Set<Stockflow> stockflows = new HashSet<Stockflow>(0);

	public Tax() {
	}

	public Tax(Resource resource, double percentage) {
		this.resource = resource;
		this.percentage = percentage;
	}

	public Tax(Resource resource, double percentage, Set<Stockflow> stockflows) {
		this.resource = resource;
		this.percentage = percentage;
		this.stockflows = stockflows;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "resource"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@Column(name = "Percentage", nullable = false, precision = 22, scale = 0)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public Set<Stockflow> getStockflows() {
		return this.stockflows;
	}

	public void setStockflows(Set<Stockflow> stockflows) {
		this.stockflows = stockflows;
	}

}
